version: '2'
services:
    app:
        image: node:8.1
        working_dir: /usr/src/app
        ports:
            - "9555:9555"
        volumes:
            - ./app:/usr/src/app
            - ~/.node_cache/geotrellis-collections-api-research-node-modules:/usr/src/app/node_modules
        command:
            yarn run start
