version: '2'
services:
    app:
        image: node:6.9
        working_dir: /usr/src/app
        ports:
            - "9555:9555"
        volumes:
            - ./app:/usr/src/app
            - ~/.node_cache/geotrellis-collections-api-research-node-modules:/usr/src/app/node_modules
        command:
            npm start
    api:
        build:
            context: ./api
            dockerfile: Dockerfile
        ports:
            - "7000:7000"
        command: ./sbt "~;jetty:stop;jetty:start"
