version: '2'
services:
    app:
        image: node:8.1
        working_dir: /usr/src/app
        ports:
            - "9555:9555"
        volumes:
            - ./app:/usr/src/app
            - ./ingest/land-cover-data/tiles:/usr/src/app/tiles
        command:
            yarn run start
